### PR TITLE
Update Discord to latest changes

### PR DESCRIPTION
**Pull request by diogoscf**
Title says it. Allows the "config" command on discord, and does the stuff it should do when it joins.

### CODE REVIEW

**Comment by diogoscf** [comment]
Oof just noticed the weird commit mess. Just squash on merge @bartekpacia

**Comment by bartekpacia** [comment]
I'll merge #33 first and then you'll probably have to fix merge conflicts. Is it ok?

**Comment by diogoscf** [comment]
Sure, but this was going into `dev` anyways, so there won't be merge conflicts

**Comment by bartekpacia** [comment]
ahh, okay then.

**Pull request merged**
