### PR TITLE
smh x2

### PR DESCRIPTION
**Pull request by diogoscf**
You went ahead and copied the mistakes you had in `except` to `remove` in your null check thing.

Smh x2

### CODE REVIEW

**Comment by bartekpacia** [comment]
I pulled the changes and already fixed them. anyway, thanks

**Comment by diogoscf** [comment]
Ah ok

**Comment by diogoscf** [comment]
Or wait it's not fixed

**Comment by bartekpacia** [comment]
forgot to push, lel

**Pull request closed without merging**
